### PR TITLE
Bizhawk 2.8

### PR DESCRIPTION
**Pull request by fenhl**
This updates the installed BizHawk version from 2.7 to 2.8. This should allow players to use the latest BizHawk improvements in multiworld etc.

### CODE REVIEW

**Comment by billygerhard** [comment]
Is there any plans to merge this PR soon? it would be nice to invite new people to play on the latest and greatest instead of older versions.

**Review by billygerhard — CHANGES_REQUESTED** [review]

**Comment by fenhl** [comment]
fwiw 2.6.2 specifically might not be a good idea due to https://github.com/TASVideos/BizHawk/issues/2787 but there's an easy workaround of opening roms from within BizHawk. @TestRunnerSRL should I revert this to 2.6.1?

**Comment by fenhl** [comment]
Why was this closed?

**Comment by TreZc0** [comment]
Bit of repo cleanup, it was already added up the dev branch.

**Comment by fenhl** [comment]
Still needs to be merged into master, since that's the branch that's linked everywhere.

**Pull request closed without merging**
